arm-animation:
  timestamp: 400
  enabled: true
block-place:
  enabled: true
payload:
  limit: 15 #in 10 seconds
  blocked-channels:
  - "wdl:request"
  - "wdl|request"
  - "fml|hs"
  - "fml:hs"
  - "fml"
  - "wdl"
kick-message: "Oops! You can't do that!"