name: 'ExploitPatch'
version: ${project.version}
main: 'xyz.yooniks.exploitpatch.bukkit.ExploitPatchPlugin'
loadbefore: ['ProtocolLib', 'ViaVersion']
depend: ['ProtocolLib']
authors: ['yooniks']
description: 'Just easily fixes nbt and payload exploits'
website: 'www.youtube.com/c/Enchanted3'